const option = (value, label = value) => ({ value, label });
const statusOption = (value, label) => ({ value, label });

export const mealCategories = [
  { key: 'all', name: '全部', sort_order: 0 },
  { key: 'package', name: '套餐', sort_order: 1 },
  { key: 'cold', name: '凉菜', sort_order: 2 },
  { key: 'hot', name: '热菜', sort_order: 3 },
  { key: 'staple', name: '主食', sort_order: 4 },
  { key: 'drink', name: '饮品', sort_order: 5 },
];

export const modules = [
  {
    key: 'home_banners',
    name: '首页轮播',
    group: '首页配置',
    idField: 'banner_id',
    titleField: 'title',
    imageFields: { image_url: 'home/banners' },
    imageRatios: { image_url: '4 / 5' },
    columns: ['image_url', 'title', 'kicker', 'is_enabled'],
    fields: [
      { key: 'banner_id', label: '轮播 ID', required: true, hidden: true },
      { key: 'image_url', label: '轮播图片', type: 'image' },
      { key: 'kicker', label: '小标题' },
      { key: 'title', label: '主标题', type: 'textarea', required: true },
      { key: 'description', label: '描述', type: 'textarea' },
      { key: 'link_type', label: '跳转类型', type: 'select', options: ['none', 'page', 'activity', 'booking', 'menu', 'webview'].map((v) => option(v)) },
      { key: 'link_target', label: '跳转目标' },
      { key: 'sort_order', label: '排序', type: 'number', hidden: true },
      { key: 'is_enabled', label: '启用', type: 'boolean' },
      { key: 'start_at', label: '定时上架', type: 'datetime' },
      { key: 'end_at', label: '定时下架', type: 'datetime' },
    ],
  },
  {
    key: 'home_quick_entries',
    name: '快捷入口',
    group: '首页配置',
    idField: 'entry_id',
    titleField: 'title',
    columns: ['title', 'icon', 'action', 'sort_order', 'is_enabled'],
    fields: [
      { key: 'entry_id', label: '入口 ID', required: true, hidden: true },
      { key: 'icon', label: '图标' },
      { key: 'title', label: '标题', required: true },
      { key: 'description', label: '描述' },
      { key: 'action', label: '动作', type: 'select', options: ['menu', 'booking', 'intro', 'activities', 'custom_page', 'webview'].map((v) => option(v)) },
      { key: 'link_target', label: '跳转目标' },
      { key: 'tone', label: '样式标记' },
      { key: 'sort_order', label: '排序', type: 'number' },
      { key: 'is_enabled', label: '启用', type: 'boolean' },
    ],
  },
  {
    key: 'home_feature_cards',
    name: '首页卡片',
    group: '首页配置',
    idField: 'card_id',
    titleField: 'title',
    imageFields: { image_url: 'home/cards' },
    columns: ['image_url', 'title', 'card_type', 'sort_order', 'is_enabled'],
    fields: [
      { key: 'card_id', label: '卡片 ID', required: true, hidden: true },
      { key: 'card_type', label: '卡片类型', type: 'select', options: ['intro', 'activity_entry', 'custom'].map((v) => option(v)) },
      { key: 'image_url', label: '卡片图片', type: 'image' },
      { key: 'title', label: '标题', required: true },
      { key: 'subtitle', label: '副标题' },
      { key: 'action', label: '动作' },
      { key: 'link_target', label: '跳转目标' },
      { key: 'sort_order', label: '排序', type: 'number' },
      { key: 'is_enabled', label: '启用', type: 'boolean' },
    ],
  },
  {
    key: 'content_pages',
    name: '图文页面',
    group: '内容管理',
    idField: 'page_id',
    titleField: 'title',
    imageFields: { cover_image_url: 'intro', content_image_url: 'intro' },
    columns: ['cover_image_url', 'title', 'page_type', 'page_status', 'is_active'],
    fields: [
      { key: 'page_id', label: '页面 ID', required: true, hidden: true },
      { key: 'page_type', label: '页面类型', type: 'select', options: ['intro', 'notice', 'custom'].map((v) => option(v)) },
      { key: 'title', label: '标题', required: true },
      { key: 'summary', label: '摘要', type: 'textarea' },
      { key: 'cover_image_url', label: '封面图', type: 'image' },
      { key: 'content_blocks', label: '内容块', type: 'contentBlocks' },
      { key: 'page_status', label: '状态', type: 'select', options: ['draft', 'published', 'offline'].map((v) => option(v)) },
      { key: 'is_active', label: '当前使用', type: 'boolean' },
      { key: 'activated_at', label: '启用时间', type: 'datetime', hidden: true },
      { key: 'activated_by', label: '启用人', hidden: true },
      { key: 'published_at', label: '发布时间', type: 'datetime' },
    ],
  },
  {
    key: 'meal_items',
    name: '菜品',
    group: '餐饮管理',
    idField: 'item_id',
    titleField: 'name',
    imageFields: { image_url: 'meal-items' },
    imageRatios: { image_url: '1 / 1' },
    columns: ['image_url', 'name', 'category_name', 'price', 'is_available'],
    fields: [
      { key: 'item_id', label: '菜品 ID', required: true, hidden: true },
      { key: 'category_key', label: '分类 key', hidden: true },
      { key: 'category_name', label: '分类名称', hidden: true },
      { key: 'category_sort_order', label: '分类排序', type: 'number', hidden: true },
      { key: 'item_type', label: '类型', type: 'select', options: ['package', 'single'].map((v) => option(v)), hidden: true },
      { key: 'name', label: '菜品名称', required: true },
      { key: 'description', label: '描述', type: 'textarea' },
      { key: 'specification', label: '规格' },
      { key: 'details', label: '套餐明细', type: 'itemDetails' },
      { key: 'price', label: '价格', type: 'number' },
      { key: 'member_price', label: '会员价', type: 'number' },
      { key: 'image_url', label: '菜品图', type: 'image' },
      { key: 'is_available', label: '可售', type: 'boolean' },
      { key: 'sort_order', label: '排序', type: 'number', hidden: true },
    ],
  },
  {
    key: 'meal_tables',
    name: '桌台',
    group: '餐饮管理',
    idField: 'table_id',
    titleField: 'table_name',
    imageFields: { qr_image_file_id: 'meal-tables' },
    imageRatios: { qr_image_file_id: '1 / 1' },
    columns: ['table_name', 'table_area', 'capacity', 'table_status', 'qr_image_file_id'],
    fields: [
      { key: 'table_id', label: '桌台 ID', required: true, hidden: true },
      { key: 'table_name', label: '桌台名称', required: true },
      { key: 'table_area', label: '区域' },
      { key: 'capacity', label: '人数', type: 'number' },
      { key: 'sort_order', label: '排序', type: 'number', hidden: true },
      { key: 'table_status', label: '状态', type: 'select', options: ['enabled', 'disabled'].map((v) => option(v)), hidden: true },
      { key: 'qr_token', label: '二维码 token', hidden: true },
      { key: 'qr_version', label: '二维码版本', type: 'number', hidden: true },
      { key: 'qr_scene', label: '二维码场景', hidden: true },
      { key: 'qr_image_file_id', label: '二维码图片', type: 'image', hidden: true },
      { key: 'current_session_id', label: '当前会话 ID', hidden: true },
    ],
  },
  {
    key: 'dining_rooms',
    name: '餐厅包间',
    group: '餐饮管理',
    idField: 'room_id',
    titleField: 'name',
    imageFields: { image_url: 'rooms' },
    columns: ['image_url', 'name', 'category', 'max_capacity', 'is_available'],
    fields: [
      { key: 'room_id', label: '包间 ID', required: true, hidden: true },
      { key: 'name', label: '包间名称', required: true },
      { key: 'category', label: '分类' },
      { key: 'min_capacity', label: '最少人数', type: 'number' },
      { key: 'max_capacity', label: '最多人数', type: 'number' },
      { key: 'image_url', label: '包间图片', type: 'image' },
      { key: 'is_available', label: '可用', type: 'boolean' },
      { key: 'sort_order', label: '排序', type: 'number', hidden: true },
    ],
  },
  {
    key: 'dining_standards',
    name: '餐标',
    group: '餐饮管理',
    idField: 'meal_standard_id',
    titleField: 'name',
    imageFields: { image_url: 'dining-standards' },
    columns: ['image_url', 'name', 'price_per_person', 'is_enabled'],
    fields: [
      { key: 'meal_standard_id', label: '餐标 ID', required: true, hidden: true },
      { key: 'name', label: '餐标名称', required: true },
      { key: 'price_per_person', label: '人均价格', type: 'number' },
      { key: 'summary', label: '摘要', type: 'textarea' },
      { key: 'dishes', label: '菜品明细', type: 'standardDishes' },
      { key: 'image_url', label: '餐标图片', type: 'image' },
      { key: 'is_enabled', label: '启用', type: 'boolean' },
      { key: 'sort_order', label: '排序', type: 'number' },
    ],
  },
  {
    key: 'accommodation_rooms',
    name: '住宿客房',
    group: '住宿管理',
    idField: 'room_id',
    titleField: 'name',
    imageFields: { image_url: 'rooms', image_urls: 'rooms' },
    columns: ['image_url', 'name', 'category', 'regular_price', 'is_available'],
    fields: [
      { key: 'room_id', label: '客房 ID', required: true, hidden: true },
      { key: 'name', label: '客房名称', required: true },
      { key: 'category', label: '房型' },
      { key: 'min_capacity', label: '最少人数', type: 'number' },
      { key: 'max_capacity', label: '最多人数', type: 'number' },
      { key: 'regular_price', label: '门市价', type: 'number' },
      { key: 'member_price', label: '会员价', type: 'number' },
      { key: 'image_url', label: '客房图片', type: 'image' },
      { key: 'image_urls', label: '客房多图', type: 'images' },
      { key: 'is_available', label: '可用', type: 'boolean' },
      { key: 'sort_order', label: '排序', type: 'number' },
    ],
  },
  {
    key: 'activity_items',
    name: '活动',
    group: '活动管理',
    idField: 'activity_id',
    titleField: 'title',
    imageFields: { image_url: 'activities' },
    columns: ['image_url', 'title', 'date', 'status', 'reserved_count'],
    fields: [
      { key: 'activity_id', label: '活动 ID', required: true, hidden: true },
      { key: 'title', label: '标题', required: true },
      { key: 'description', label: '描述', type: 'textarea' },
      { key: 'list_description', label: '列表描述', type: 'textarea' },
      { key: 'detail_summary', label: '详情摘要', type: 'textarea' },
      { key: 'intro', label: '介绍 JSON', type: 'json' },
      { key: 'notice', label: '须知', type: 'textarea' },
      { key: 'image_url', label: '活动图', type: 'image' },
      { key: 'date', label: '日期' },
      { key: 'time', label: '时间' },
      { key: 'location', label: '地点' },
      { key: 'start_at', label: '开始时间', type: 'datetime' },
      { key: 'end_at', label: '结束时间', type: 'datetime' },
      { key: 'signup_deadline', label: '报名截止', type: 'datetime' },
      { key: 'signup_scope', label: '报名范围', type: 'select', options: ['public', 'members_only'].map((v) => option(v)) },
      { key: 'fee_type', label: '费用类型', type: 'select', options: ['free', 'paid'].map((v) => option(v)) },
      { key: 'guest_price', label: '散客价', type: 'number' },
      { key: 'member_price', label: '会员价', type: 'number' },
      { key: 'capacity', label: '容量', type: 'number' },
      { key: 'reserved_count', label: '已报名', type: 'number' },
      { key: 'status', label: '状态', type: 'select', options: ['open', 'full', 'closed'].map((v) => option(v)) },
      { key: 'status_tone', label: '状态样式' },
      { key: 'sort_order', label: '排序', type: 'number' },
    ],
  },
  {
    key: 'members',
    name: '会员档案',
    group: '会员管理',
    idField: 'member_id',
    titleField: 'member_name',
    columns: ['member_name', 'mobile', 'member_level', 'member_status', 'points_balance'],
    fields: [
      { key: 'member_id', label: '会员 ID', required: true, hidden: true },
      { key: 'mobile', label: '手机号', required: true },
      { key: 'member_name', label: '姓名', required: true },
      { key: 'level_id', label: '会员等级', type: 'memberLevelSelect', required: true },
      { key: 'member_level', label: '等级名称', hidden: true },
      { key: 'member_status', label: '状态', type: 'select', options: [
        statusOption('active', '生效中'),
        statusOption('expired', '已到期'),
        statusOption('disabled', '已停用'),
      ] },
      { key: 'benefit_start_at', label: '权益开始', type: 'datetime' },
      { key: 'benefit_end_at', label: '权益结束', type: 'datetime' },
      { key: 'points_balance', label: '积分余额', type: 'number' },
      { key: '__memberBenefitRows', label: '个人权益明细', type: 'memberBenefits' },
    ],
  },
  {
    key: 'member_levels',
    name: '会员等级与权益',
    group: '会员管理',
    idField: 'level_id',
    titleField: 'level_name',
    columns: ['level_name', 'stored_amount', 'points_granted', 'valid_months', 'is_enabled'],
    fields: [
      { key: 'level_id', label: '等级 ID', required: true, hidden: true },
      { key: 'level_no', label: '等级序号', type: 'number' },
      { key: 'level_name', label: '等级名称', required: true },
      { key: 'stored_amount', label: '储值金额', type: 'number' },
      { key: 'points_granted', label: '赠送积分', type: 'number' },
      { key: 'valid_months', label: '有效月数', type: 'number' },
      { key: 'description', label: '说明', type: 'textarea' },
      { key: 'is_enabled', label: '启用', type: 'boolean' },
      { key: 'sort_order', label: '排序', type: 'number', hidden: true },
      { key: '__levelBenefitRows', label: '等级权益', type: 'levelBenefits' },
    ],
  },
  {
    key: 'member_level_benefits',
    name: '等级权益',
    group: '会员管理',
    hiddenInNav: true,
    idField: 'level_benefit_id',
    titleField: 'benefit_name',
    columns: ['benefit_name', 'level_id', 'benefit_type', 'total_quota', 'show_on_card', 'is_enabled'],
    fields: [
      { key: 'level_benefit_id', label: '权益 ID', required: true, hidden: true },
      { key: 'level_id', label: '等级 ID', hidden: true },
      { key: 'benefit_key', label: '权益 key', hidden: true },
      { key: 'benefit_name', label: '权益名称' },
      { key: 'benefit_type', label: '权益类型', type: 'select', options: [
        option('service', '服务权益'),
        option('quota', '次数权益'),
      ] },
      { key: 'total_quota', label: '总次数', type: 'number' },
      { key: 'quota_unit', label: '单位' },
      { key: 'description', label: '权益说明', type: 'textarea' },
      { key: 'show_on_card', label: '显示在会员卡', type: 'boolean' },
      { key: 'applies_to', label: '适用业务 JSON', type: 'json', hidden: true },
      { key: 'rule', label: '规则 JSON', type: 'json', hidden: true },
      { key: 'is_enabled', label: '启用', type: 'boolean' },
      { key: 'sort_order', label: '排序', type: 'number', hidden: true },
    ],
  },
  {
    key: 'member_benefit_accounts',
    name: '会员权益账户',
    group: '会员管理',
    hiddenInNav: true,
    idField: 'benefit_account_id',
    titleField: 'benefit_name',
    columns: ['benefit_name', 'member_id', 'benefit_type', 'remaining_quota', 'account_status'],
    fields: [
      { key: 'benefit_account_id', label: '账户 ID', required: true, hidden: true },
      { key: 'member_id', label: '会员 ID', required: true, hidden: true },
      { key: 'level_id', label: '等级 ID', hidden: true },
      { key: 'benefit_key', label: '权益 key', required: true, hidden: true },
      { key: 'benefit_name', label: '权益名称', required: true },
      { key: 'benefit_type', label: '权益类型', type: 'select', options: [
        option('service', '服务权益'),
        option('quota', '次数权益'),
      ] },
      { key: 'total_quota', label: '总次数', type: 'number' },
      { key: 'used_quota', label: '已用次数', type: 'number' },
      { key: 'locked_quota', label: '锁定次数', type: 'number' },
      { key: 'remaining_quota', label: '剩余次数', type: 'number' },
      { key: 'quota_unit', label: '单位' },
      { key: 'valid_start_at', label: '有效开始', type: 'datetime' },
      { key: 'valid_end_at', label: '有效结束', type: 'datetime' },
      { key: 'account_status', label: '账户状态', type: 'select', options: [
        statusOption('active', '生效中'),
        statusOption('expired', '已到期'),
        statusOption('disabled', '已停用'),
      ] },
    ],
  },
  {
    key: 'dining_reservations',
    name: '用餐预约',
    group: '订单预约',
    idField: 'reservation_id',
    titleField: 'order_no',
    columns: ['order_no', 'customer_name', 'customer_mobile', 'reservation_date', 'reservation_status'],
    fields: [
      { key: 'reservation_id', label: '预约 ID', hidden: true },
      { key: 'order_no', label: '订单号' },
      { key: 'customer_name', label: '联系人' },
      { key: 'customer_mobile', label: '手机号' },
      { key: 'reservation_date', label: '日期' },
      { key: 'reservation_time', label: '时间' },
      { key: 'guest_count', label: '人数', type: 'number' },
      { key: 'room_id', label: '包间 ID' },
      { key: 'room_name', label: '包间名称' },
      { key: 'meal_standard_id', label: '餐标 ID' },
      { key: 'meal_standard_name', label: '餐标名称' },
      { key: 'reservation_status', label: '状态', type: 'reservationStatus' },
      { key: 'remark', label: '备注', type: 'textarea' },
      { key: 'admin_remark', label: '后台备注', type: 'textarea' },
    ],
  },
  {
    key: 'accommodation_reservations',
    name: '住宿预约',
    group: '订单预约',
    idField: 'reservation_id',
    titleField: 'order_no',
    columns: ['order_no', 'customer_name', 'customer_mobile', 'checkin_date', 'reservation_status'],
    fields: [
      { key: 'reservation_id', label: '预约 ID', hidden: true },
      { key: 'order_no', label: '订单号' },
      { key: 'customer_name', label: '联系人' },
      { key: 'customer_mobile', label: '手机号' },
      { key: 'checkin_date', label: '入住日期' },
      { key: 'checkout_date', label: '离店日期' },
      { key: 'guest_count', label: '人数', type: 'number' },
      { key: 'room_id', label: '客房 ID' },
      { key: 'room_name', label: '客房名称' },
      { key: 'reservation_status', label: '状态', type: 'reservationStatus' },
      { key: 'remark', label: '备注', type: 'textarea' },
      { key: 'admin_remark', label: '后台备注', type: 'textarea' },
    ],
  },
  {
    key: 'activity_signups',
    name: '活动报名',
    group: '订单预约',
    idField: 'signup_id',
    titleField: 'order_no',
    columns: ['order_no', 'activity_title', 'contact_name', 'participant_count', 'signup_status'],
    fields: [
      { key: 'signup_id', label: '报名 ID', hidden: true },
      { key: 'order_no', label: '订单号' },
      { key: 'activity_id', label: '活动 ID' },
      { key: 'activity_title', label: '活动标题' },
      { key: 'contact_name', label: '联系人' },
      { key: 'contact_mobile', label: '手机号' },
      { key: 'participant_count', label: '人数', type: 'number' },
      { key: 'signup_status', label: '状态' },
      { key: 'remark', label: '备注', type: 'textarea' },
      { key: 'admin_remark', label: '后台备注', type: 'textarea' },
    ],
  },
  {
    key: 'meal_orders',
    name: '点餐订单',
    group: '订单预约',
    idField: 'order_id',
    titleField: 'order_no',
    columns: ['order_no', 'table_name', 'total_amount', 'order_status', 'payment_status'],
    fields: [
      { key: 'order_id', label: '订单 ID', hidden: true },
      { key: 'order_no', label: '订单号' },
      { key: 'table_id', label: '桌台 ID' },
      { key: 'table_name', label: '桌台名称' },
      { key: 'customer_name', label: '联系人' },
      { key: 'customer_mobile', label: '手机号' },
      { key: 'items', label: '菜品 JSON', type: 'json' },
      { key: 'total_amount', label: '总金额', type: 'number' },
      { key: 'pay_amount', label: '实付金额', type: 'number' },
      { key: 'order_status', label: '订单状态' },
      { key: 'payment_status', label: '支付状态' },
      { key: 'remark', label: '备注', type: 'textarea' },
      { key: 'admin_remark', label: '后台备注', type: 'textarea' },
    ],
  },
];

export const groupedModules = modules.filter((item) => !item.hiddenInNav).reduce((groups, item) => {
  const group = groups.find((entry) => entry.name === item.group);
  if (group) group.items.push(item);
  else groups.push({ name: item.group, items: [item] });
  return groups;
}, []);
